# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'AppBuilders' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  pod 'react-native-mail', :path => '../node_modules/react-native-mail'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'AppBuildersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AppBuilders-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  target 'AppBuilders-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
